export type Permission = (typeof permissions)[number]['key'];

export const permissions = [
  {
    key: 'GetBackendConfigs',
    method: 'GET',
    url: '/auction-master/backend/configs',
    description: '取得系統設定擋',
  },
  {
    key: 'GetRoles',
    method: 'GET',
    url: '/auction-master/backend/roles',
    description: '取得所有角色',
  },
  {
    key: 'GetRolesPermission',
    method: 'GET',
    url: '/auction-master/backend/roles/permissions',
    description: '取得所有權限',
  },
  {
    key: 'CreateRole',
    method: 'POST',
    url: '/auction-master/backend/roles',
    description: '新增角色',
  },
  {
    key: 'DeleteRole',
    method: 'DELETE',
    url: '/auction-master/backend/roles/:role',
    description: '刪除角色',
  },
  {
    key: 'GetPermissions',
    method: 'GET',
    url: '/auction-master/backend/permissions',
    description: '取得所有角色的權限',
  },
  {
    key: 'AddPermissionForRole',
    method: 'POST',
    url: '/auction-master/backend/permissions',
    description: '新增角色的權限',
  },
  {
    key: 'DeletePermissionForRole',
    method: 'DELETE',
    url: '/auction-master/backend/permissions',
    description: '刪除角色的權限',
  },
  {
    key: 'GetUsersForRole',
    method: 'GET',
    url: '/auction-master/backend/roles/:role',
    description: '取得角色使用者列表',
  },
  {
    key: 'AddRoleForUser',
    method: 'POST',
    url: '/auction-master/backend/roles/account/:account',
    description: '新增使用者的角色',
  },
  {
    key: 'DeleteRoleForUser',
    method: 'DELETE',
    url: '/auction-master/backend/roles/account/:account',
    description: '刪除使用者的角色',
  },
  {
    key: 'GetAdmins',
    method: 'GET',
    url: '/auction-master/backend/admins',
    description: '取得後台帳號列表',
  },
  {
    key: 'GetAdmin',
    method: 'GET',
    url: '/auction-master/backend/admins/:id',
    description: '取得後台帳號',
  },
  {
    key: 'CreateAdmin',
    method: 'POST',
    url: '/auction-master/backend/admins',
    description: '建立後台帳號',
  },
  {
    key: 'UpdateAdmin',
    method: 'PATCH',
    url: '/auction-master/backend/admins/:id',
    description: '修改後台帳號資訊',
  },
  {
    key: 'UpdateAdminPassword',
    method: 'PATCH',
    url: '/auction-master/backend/admins/:id/password',
    description: '修改後台密碼',
  },
  {
    key: 'DeleteAdmin',
    method: 'DELETE',
    url: '/auction-master/backend/admins/:id',
    description: '刪除後台帳號',
  },
  {
    key: 'GetWorkers',
    method: 'GET',
    url: '/auction-master/backend/workers',
    description: '取得 Worker 列表',
  },
  {
    key: 'GetActivationWorkers',
    method: 'GET',
    url: '/auction-master/backend/workers/activation',
    description: '取得啟用中的 Worker 列表',
  },
  {
    key: 'CreateWorker',
    method: 'POST',
    url: '/auction-master/backend/workers',
    description: '新增 Worker',
  },
  {
    key: 'SetWorkerCookie',
    method: 'POST',
    url: '/auction-master/backend/workers/:id/cookie',
    description: '設定 Worker 日拍 Cookie',
  },
  {
    key: 'ToggleActivateWorker',
    method: 'PATCH',
    url: '/auction-master/backend/workers/:id/:status',
    description: '修改 Worker 狀態',
  },
  {
    key: 'UpdateWorker',
    method: 'PATCH',
    url: '/auction-master/backend/workers/:id',
    description: '修改 Worker',
  },
  {
    key: 'DeleteWorker',
    method: 'DELETE',
    url: '/auction-master/backend/workers/:id',
    description: '刪除 Worker',
  },
  {
    key: 'GetAuctionItems',
    method: 'GET',
    url: '/auction-master/backend/auction-items',
    description: '取得日拍競標商品列表',
  },
  {
    key: 'CreateAuctionItem',
    method: 'POST',
    url: '/auction-master/backend/auction-items',
    description: '建立日拍競標商品',
  },
  {
    key: 'UpdateAuctionItem',
    method: 'PATCH',
    url: '/auction-master/backend/auction-items/:id',
    description: '修改日拍競標商品',
  },
  {
    key: 'ToggleActivateAuctionItem',
    method: 'PATCH',
    url: '/auction-master/backend/auction-items/:id/:status',
    description: '修改日拍競標商品狀態',
  },
  {
    key: 'AuctionItemDealPreview',
    method: 'GET',
    url: '/auction-master/backend/auction-items/:id/deal/preview',
    description: '取得日拍競標商品成交預覽',
  },
  {
    key: 'DealAuctionItem',
    method: 'POST',
    url: '/auction-master/backend/auction-items/:id/deal',
    description: '日拍競標商品成交',
  },
  {
    key: 'GetConsignors',
    method: 'GET',
    url: '/auction-master/backend/consignors',
    description: '取得寄售人列表',
  },
  {
    key: 'AdminUpdateConsignor',
    method: 'PATCH',
    url: '/auction-master/backend/consignors/:id',
    description: '管理者修改寄售人資訊',
  },
  {
    key: 'GetConsignorVerifications',
    method: 'GET',
    url: '/auction-master/backend/consignors/verifications',
    description: '取得寄售人身分驗證列表',
  },
  {
    key: 'HandleConsignorVerification',
    method: 'POST',
    url: '/auction-master/backend/consignors/verifications/:id/:action',
    description: '審核寄售人身分驗證',
  },
  {
    key: 'GetItems',
    method: 'GET',
    url: '/auction-master/backend/items',
    description: '取得物品列表',
  },
  {
    key: 'UpdateItem',
    method: 'PATCH',
    url: '/auction-master/backend/items/:id',
    description: '修改物品',
  },
  {
    key: 'UpsertItemPhoto',
    method: 'PATCH',
    url: '/auction-master/backend/items/:id/photo',
    description: '上傳物品照片',
  },
  {
    key: 'ItemAppraisalReview',
    method: 'POST',
    url: '/auction-master/backend/items/:id/review',
    description: '審核寄售人物品',
  },
  {
    key: 'ItemArrival',
    method: 'POST',
    url: '/auction-master/backend/items/:id/arrival',
    description: '物品到貨處理',
  },
  {
    key: 'ItemReturned',
    method: 'POST',
    url: '/auction-master/backend/items/:id/return',
    description: '已退回物品',
  },
  {
    key: 'ItemCompleteDetails',
    method: 'POST',
    url: '/auction-master/backend/items/:id/complete-details',
    description: '上架資料齊全',
  },
  {
    key: 'ItemBidding',
    method: 'POST',
    url: '/auction-master/backend/items/:id/bidding',
    description: '物品上架',
  },
  {
    key: 'ItemReclaimed',
    method: 'POST',
    url: '/auction-master/backend/items/:id/reclaimed',
    description: '物品收回',
  },
] as const;
