import { mapToObj } from 'remeda';

export const PERMISSIONS_DATA = [
  {
    message: '系統相關',
    permissions: [
      {
        key: 'StartBackendWs',
        url: '/auction-master/backend/ws',
        method: 'GET',
        fields: ['*'],
        description: '使用通訊功能',
      },
      {
        key: 'GetConfigs',
        url: '/auction-master/backend/configs',
        method: 'GET',
        fields: ['*'],
        description: '取得系統設定擋',
      },
      {
        key: 'GetBackendStaticConfigs',
        url: '/auction-master/backend/static-configs',
        method: 'GET',
        fields: ['*'],
        description: '取得系統靜態設定擋',
      },
      {
        key: 'GetJpyRates',
        url: '/auction-master/backend/jpy-rates',
        method: 'GET',
        fields: ['*'],
        description: '取得日幣匯率',
      },
    ],
  },
  {
    message: '角色相關',
    permissions: [
      {
        key: 'GetRoles',
        url: '/auction-master/backend/roles',
        method: 'GET',
        fields: ['*'],
        description: '取得所有角色',
      },
      {
        key: 'GetRolePermissions',
        url: '/auction-master/backend/roles/:role/permissions',
        method: 'GET',
        fields: ['*'],
        description: '取得角色的權限',
      },
      {
        key: 'CreateRole',
        url: '/auction-master/backend/roles',
        method: 'POST',
        fields: ['*'],
        description: '新增角色',
      },
      {
        key: 'DeleteRole',
        url: '/auction-master/backend/roles/:role',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除角色',
      },
      {
        key: 'GetPermissions',
        url: '/auction-master/backend/permissions',
        method: 'GET',
        fields: ['*'],
        description: '取得所有權限',
      },
      {
        key: 'GetAdminPermissions',
        url: '/auction-master/backend/permissions/:account',
        method: 'GET',
        fields: ['*'],
        description: '取得管理者擁有的權限',
      },
      {
        key: 'AddPermissionForRole',
        url: '/auction-master/backend/permissions',
        method: 'POST',
        fields: ['*'],
        description: '新增角色的權限',
      },
      {
        key: 'DeletePermissionForRole',
        url: '/auction-master/backend/permissions',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除角色的權限',
      },
    ],
  },
  {
    message: '管理者相關',
    permissions: [
      {
        key: 'GetAdmins',
        url: '/auction-master/backend/admins',
        method: 'GET',
        fields: ['*'],
        description: '取得後台帳號列表',
      },
      {
        key: 'GetAdmin',
        url: '/auction-master/backend/admins/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得後台帳號',
      },
      {
        key: 'CreateAdmin',
        url: '/auction-master/backend/admins',
        method: 'POST',
        fields: ['*'],
        description: '建立後台帳號',
      },
      {
        key: 'AddRoleForAdmin',
        url: '/auction-master/backend/admins/account/:account/roles',
        method: 'POST',
        fields: ['*'],
        description: '新增管理者的角色',
      },
      {
        key: 'DeleteRoleForAdmin',
        url: '/auction-master/backend/admins/account/:account/roles',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除管理者的角色',
      },
      {
        key: 'UpdateAdmin',
        url: '/auction-master/backend/admins/:id',
        method: 'PATCH',
        fields: ['account', 'password', 'status'],
        description: '修改後台帳號資訊',
      },
      {
        key: 'UpdateAdminPassword',
        url: '/auction-master/backend/admins/:id/password',
        method: 'PATCH',
        fields: ['*'],
        description: '修改後台密碼',
      },
      {
        key: 'DeleteAdmin',
        url: '/auction-master/backend/admins/:id',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除後台帳號',
      },
    ],
  },
  {
    message: '盯標相關',
    permissions: [
      {
        key: 'GetWorkers',
        url: '/auction-master/backend/workers',
        method: 'GET',
        fields: ['*'],
        description: '取得 Worker 列表',
      },
      {
        key: 'GetActivationWorkers',
        url: '/auction-master/backend/workers/activation',
        method: 'GET',
        fields: ['*'],
        description: '取得啟用中的 Worker 列表',
      },
      {
        key: 'GetWorker',
        url: '/auction-master/backend/workers/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得 Worker',
      },
      {
        key: 'CreateWorker',
        url: '/auction-master/backend/workers',
        method: 'POST',
        fields: ['*'],
        description: '新增 Worker',
      },
      {
        key: 'SetWorkerCookie',
        url: '/auction-master/backend/workers/:id/cookie',
        method: 'POST',
        fields: ['*'],
        description: '設定 Worker 日拍 Cookie',
      },
      {
        key: 'ToggleActivateWorker',
        url: '/auction-master/backend/workers/:id/:status',
        method: 'PATCH',
        fields: ['*'],
        description: '修改 Worker 狀態',
      },
      {
        key: 'UpdateWorker',
        url: '/auction-master/backend/workers/:id',
        method: 'PATCH',
        fields: [
          'type',
          'url',
          'account',
          'name',
          'phone',
          'postalCode',
          'birthday',
          'email',
          'simCardNumber',
          'activationAt',
          'remark',
          'status',
        ],
        description: '修改 Worker',
      },
      {
        key: 'DeleteWorker',
        url: '/auction-master/backend/workers/:id',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除 Worker',
      },
    ],
  },
  {
    message: '競標物品相關',
    permissions: [
      {
        key: 'GetAuctionItems',
        url: '/auction-master/backend/auction-items',
        method: 'GET',
        fields: ['*'],
        description: '取得日拍競標商品列表',
      },
      {
        key: 'GetAuctionItem',
        url: '/auction-master/backend/auction-items/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得日拍競標商品',
      },
      {
        key: 'CreateAuctionItem',
        url: '/auction-master/backend/auction-items',
        method: 'POST',
        fields: ['*'],
        description: '建立日拍競標商品',
      },
      {
        key: 'BidAuctionItem',
        url: '/auction-master/backend/auction-items/:id/bid',
        method: 'POST',
        fields: ['*'],
        description: '下標日拍競標商品',
      },
      {
        key: 'UpdateAuctionItem',
        url: '/auction-master/backend/auction-items/:id',
        method: 'PATCH',
        fields: [
          'consignorID',
          'itemID',
          'sellerID',
          'watcherID',
          'auctionID',
          'name',
          'photo',
          'reservePrice',
          'currentPrice',
          'highestPrice',
          'closeAt',
          'closedPrice',
          'shippingCostsWithinJapan',
          'status',
        ],
        description: '修改日拍競標商品',
      },
      {
        key: 'ToggleActivateAuctionItem',
        url: '/auction-master/backend/auction-items/:id/:status',
        method: 'PATCH',
        fields: ['*'],
        description: '修改日拍競標商品狀態',
      },
      {
        key: 'DeleteAuctionItem',
        url: '/auction-master/backend/auction-items/:id',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除日拍競標商品',
      },
      {
        key: 'AuctionItemDealPreview',
        url: '/auction-master/backend/auction-items/:id/deal/preview',
        method: 'GET',
        fields: ['*'],
        description: '取得日拍競標商品成交預覽',
      },
      {
        key: 'ShippingAuctionItem',
        url: '/auction-master/backend/auction-items/shipping',
        method: 'POST',
        fields: ['*'],
        description: '日拍競標商品出貨',
      },
      {
        key: 'CompanyPurchased',
        url: '/auction-master/backend/auction-items/:id/company-purchased',
        method: 'POST',
        fields: ['*'],
        description: '公司買回物品',
      },
    ],
  },
  {
    message: '寄售人相關',
    permissions: [
      {
        key: 'AdminGetConsignors',
        url: '/auction-master/backend/consignors',
        method: 'GET',
        fields: ['*'],
        description: '取得寄售人列表',
      },
      {
        key: 'AdminGetConsignor',
        url: '/auction-master/backend/consignors/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得寄售人',
      },
      {
        key: 'AdminUpdateConsignor',
        url: '/auction-master/backend/consignors/:id',
        method: 'PATCH',
        fields: [
          'avatar',
          'account',
          'password',
          'nickname',
          'commissionBonusRate',
          'name',
          'identification',
          'gender',
          'birthday',
          'city',
          'district',
          'streetAddress',
          'phone',
          'beneficiaryName',
          'bankCode',
          'bankAccount',
          'status',
        ],
        description: '管理者修改寄售人資訊',
      },
      {
        key: 'AdminGetConsignorVerifications',
        url: '/auction-master/backend/consignors/verifications',
        method: 'GET',
        fields: ['*'],
        description: '取得寄售人身分驗證列表',
      },
      {
        key: 'HandleConsignorVerification',
        url: '/auction-master/backend/consignors/verifications/:id/:action',
        method: 'POST',
        fields: ['*'],
        description: '審核寄售人身分驗證',
      },
    ],
  },
  {
    message: '紀錄相關',
    permissions: [
      {
        key: 'AdminGetWalletLogs',
        url: '/auction-master/backend/wallets/logs',
        method: 'GET',
        fields: ['*'],
        description: '取得錢包紀錄',
      },
      {
        key: 'AdminGetBonusLogs',
        url: '/auction-master/backend/bonuses/logs',
        method: 'GET',
        fields: ['*'],
        description: '取得紅利紀錄',
      },
    ],
  },
  {
    message: '物品相關',
    permissions: [
      {
        key: 'GetItemsAndDetails',
        url: '/auction-master/backend/items',
        method: 'GET',
        fields: ['*'],
        description: '取得物品與細項列表',
      },
      {
        key: 'GetItemAndDetails',
        url: '/auction-master/backend/items/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得物品與細項',
      },
      {
        key: 'AdminUpdateItem',
        url: '/auction-master/backend/items/:id',
        method: 'PATCH',
        fields: [
          'id',
          'consignorID',
          'type',
          'isNew',
          'name',
          'description',
          'directPurchasePrice',
          'minEstimatedPrice',
          'maxEstimatedPrice',
          'reservePrice',
          'expireAt',
          'warehouseID',
          'space',
          'shippingCostsWithinJapan',
          'grossWeight',
          'volumetricWeight',
          'status',
        ],
        description: '修改物品',
      },
      {
        key: 'AdminUpsertItemPhoto',
        url: '/auction-master/backend/items/:id/photos',
        method: 'POST',
        fields: ['*'],
        description: '上傳物品照片',
      },
      {
        key: 'AdminReorderItemPhoto',
        url: '/auction-master/backend/items/:id/photos',
        method: 'PATCH',
        fields: ['*'],
        description: '重新排序物品照片',
      },
      {
        key: 'AdminDeleteItemPhoto',
        url: '/auction-master/backend/items/:id/photos/:sorted',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除物品照片',
      },
      {
        key: 'DeleteAllItemPhotos',
        url: '/auction-master/backend/items/photos',
        method: 'DELETE',
        fields: ['*'],
        description: '刪除所有物品照片',
      },
      {
        key: 'ItemAppraisalReview',
        url: '/auction-master/backend/items/:id/review',
        method: 'POST',
        fields: ['*'],
        description: '審核寄售人物品',
      },
      {
        key: 'ItemArrival',
        url: '/auction-master/backend/items/:id/arrival',
        method: 'POST',
        fields: ['*'],
        description: '物品到貨',
      },
      {
        key: 'ItemReturnPending',
        url: '/auction-master/backend/items/:id/return-pending',
        method: 'POST',
        fields: ['*'],
        description: '等待退貨',
      },
      {
        key: 'ItemReturning',
        url: '/auction-master/backend/items/returning',
        method: 'POST',
        fields: ['*'],
        description: '退貨中',
      },
      {
        key: 'ItemWarehousePersonnelConfirmed',
        url: '/auction-master/backend/items/:id/warehouse-personnel-confirmed',
        method: 'POST',
        fields: ['*'],
        description: '倉管已確認',
      },
      {
        key: 'ItemAppraiserConfirmed',
        url: '/auction-master/backend/items/:id/appraiser-confirmed',
        method: 'POST',
        fields: ['*'],
        description: '鑑價師已確認',
      },
      {
        key: 'ItemBidding',
        url: '/auction-master/backend/items/:id/bidding',
        method: 'POST',
        fields: ['*'],
        description: '物品上架',
      },
      {
        key: 'ItemReclaimed',
        url: '/auction-master/backend/items/:id/reclaimed',
        method: 'POST',
        fields: ['*'],
        description: '物品收回',
      },
    ],
  },
  {
    message: '出貨相關',
    permissions: [
      {
        key: 'GetShippings',
        url: '/auction-master/backend/shippings',
        method: 'GET',
        fields: ['*'],
        description: '取得出貨列表',
      },
      {
        key: 'GetShipping',
        url: '/auction-master/backend/shippings/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得出貨單',
      },
      {
        key: 'UpdateShipping',
        url: '/auction-master/backend/shippings/:id',
        method: 'PATCH',
        fields: [
          'actionType',
          'shipmentType',
          'itemIDs',
          'auctionItemIDs',
          'address',
          'storeNumber',
          'storeName',
          'recipientName',
          'phone',
          'shipmentTrackingNumber',
          'internationalShippingCosts',
          'remark',
          'status',
        ],
        description: '修改出貨單',
      },
      {
        key: 'ProcessingShipping',
        url: '/auction-master/backend/shippings/:id/processing',
        method: 'POST',
        fields: ['*'],
        description: '理貨中',
      },
      {
        key: 'Shipped',
        url: '/auction-master/backend/shippings/:id/shipped',
        method: 'POST',
        fields: ['*'],
        description: '已寄出',
      },
      {
        key: 'ShippingClosed',
        url: '/auction-master/backend/shippings/:id/closed',
        method: 'POST',
        fields: ['*'],
        description: '出貨已結束',
      },
    ],
  },
  {
    message: '報表相關',
    permissions: [
      {
        key: 'GetReports',
        url: '/auction-master/backend/reports',
        method: 'GET',
        fields: ['*'],
        description: '取得報表列表',
      },
      {
        key: 'GetRecordsSummary',
        url: '/auction-master/backend/reports/records/summary',
        method: 'GET',
        fields: ['*'],
        description: '取得報表紀錄總結',
      },
      {
        key: 'GetRecords',
        url: '/auction-master/backend/reports/records',
        method: 'GET',
        fields: ['*'],
        description: '取得交易紀錄列表',
      },
      {
        key: 'GetRecord',
        url: '/auction-master/backend/reports/records/:id',
        method: 'GET',
        fields: ['*'],
        description: '取得交易紀錄',
      },
      {
        key: 'RecordPaymentReview',
        url: '/auction-master/backend/reports/records/:id/review',
        method: 'POST',
        fields: ['*'],
        description: '審核付款紀錄',
      },
    ],
  },
] as const;

export const PERMISSION_MAP = mapToObj(PERMISSIONS_DATA.map((x) => x.permissions).flat(), (x) => [x.key, x] as const);
